name: Build
on: 
  push:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build
      run: go build -v ./...

    - name: Release branch name
      id: release_branch_name
      run: |
        branch=latest

        if [[ $GITHUB_REF != refs/heads/main ]]; then
          branch=dev-${GITHUB_REF#refs/heads/}
        fi

        echo "branch=$branch"
        echo "branch=$branch" >> $GITHUB_OUTPUT

    - name: Copy release files
      run: | 
        mkdir -p release
        cp go.mod go.sum main.go action.yaml entrypoint.sh release/
        
    - name: Publish into release branch
      uses: s0/git-publish-subdir-action@v2.6.0
      env:
        REPO: self
        BRANCH: ${{ steps.release_branch_name.outputs.branch }}
        FOLDER: release
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}